import React from "react";

import prisma from "../../lib/utils";

import Container from "@/components/Container";
import Blogpost from "@/components/Blogpost";

export const metadata = {
  title: "projects",
  description: "Generated by create next app",
};

export default async function page() {
  const projects = await prisma.project.findMany({
    orderBy: {
      createdAt: "asc",
    },
  });

  return (
    <Container>
      <div className="my-20">
        <div className=" flex justify-between">
          <div className="space-y-6">
            <h1 className="text-7xl font-bold">Projects</h1>
            <h2>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Molestias, provident.
            </h2>
          </div>
        </div>
        <Blogpost data={projects} />
      </div>
    </Container>
  );
}
