import React from "react";
import Image from "next/image";
import prisma from "../../lib/utils";
import Link from "next/link";
import Container from "@/components/Container";

export const metadata = {
  title: "projects",
  description: "Generated by create next app",
};

export default async function page() {
  const projects = await prisma.project.findMany({
    orderBy: {
      createdAt: "asc",
    },
  });

  return (
    <Container>
      <div className="flex flex-wrap my-10 -mx-4">
        {projects.map((item, idx) => {
          return (
            <div key={idx} className="w-full px-4 mb-8 md:w-1/2 lg:w-1/2">
              <div className="h-full overflow-hidden border-2 border-gray-200 rounded-lg border-opacity-60">
                <Image
                  className="w-full lg:h-96 md:h-36 hover:blur-sm"
                  height={1000}
                  width={1000}
                  src={`/${item.img}.png`}
                  alt={item.title}
                />
                <div className="p-6">
                  <h2 className="mb-1 text-xs font-medium tracking-widest text-gray-400 title-font">
                    SOFTWARE ENGINEER
                  </h2>
                  <div className="flex justify-between">
                    <h1 className="mb-3 text-lg font-medium text-gray-900 title-font">
                      {item.title}
                    </h1>
                    <div className="flex items-center space-x-2">
                      <p className="bg-[#1b1b1b] text-white px-3 rounded-full">
                        Solidity
                      </p>
                      <p className="bg-[#efd81d] px-3 rounded-full">
                        JavaScript
                      </p>
                    </div>
                  </div>
                  <p className="mb-3 leading-relaxed">
                    {item.body.slice(0, 200)}...
                  </p>
                  <div className="flex flex-wrap items-center">
                    <Link
                      href={`projects/${item.slug}`}
                      className="inline-flex items-center text-indigo-500 md:mb-2 lg:mb-0"
                    >
                      Learn More
                      <svg
                        className="w-4 h-4 ml-2"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        strokeWidth="2"
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M5 12h14"></path>
                        <path d="M12 5l7 7-7 7"></path>
                      </svg>
                    </Link>
                    <span className="inline-flex items-center py-1 pr-3 ml-auto mr-3 text-sm leading-none text-gray-400 border-r-2 border-gray-200 lg:ml-auto md:ml-0">
                      <svg
                        className="w-4 h-4 mr-1"
                        stroke="currentColor"
                        strokeWidth="2"
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        viewBox="0 0 24 24"
                      >
                        <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                        <circle cx="12" cy="12" r="3"></circle>
                      </svg>
                      Github
                    </span>
                    <span className="inline-flex items-center text-sm leading-none text-gray-400">
                      <svg
                        className="w-4 h-4 mr-1"
                        stroke="currentColor"
                        stroke-width="2"
                        fill="none"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        viewBox="0 0 24 24"
                      >
                        <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                      </svg>
                      Website
                    </span>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </Container>
  );
}
