import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata: Metadata = {
  title: { default: "kadynpearce", template: "kadynpearce/%s" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang="en">
        <body className="mx-auto container px-4 lg:px-0 ">
          <Navbar />
          {children}
        </body>
      </html>
    </UserProvider>
  );
}
